version: '3.8'
services:
  pocketbase:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - '7090:7090'
    volumes:
      - ./data:/pb/data
    networks:
      - pocketbase

  subscription_service:
    depends_on:
      - pocketbase
    restart: always
    image: ghcr.io/budgetbuddyde/subscription-service:latest-dev
    environment:
      - ENV=production
      - POCKETBASE_URL=${POCKETBASE_URL}
      - SERVICE_ACCOUNT_EMAIL=${SUBSCRIPTION_SERVICE_SERVICE_ACCOUNT_EMAIL}
      - SERVICE_ACCOUNT_PASSWORD=${SUBSCRIPTION_SERVICE_SERVICE_ACCOUNT_PASSWORD}
    networks:
      - pocketbase

  stock_service:
    depends_on:
      - pocketbase
    restart: always
    image: ghcr.io/budgetbuddyde/stock-service:latest-dev
    environment:
      - ENV=production
      - PORT=7070
      - POCKETBASE_URL=${POCKETBASE_URL}
      - SERVICE_ACCOUNT_EMAIL=${STOCK_SERVICE_SERVICE_ACCOUNT_EMAIL}
      - SERVICE_ACCOUNT_PASSWORD=${STOCK_SERVICE_SERVICE_ACCOUNT_PASSWORD}
      - STOCK_API_URL=${STOCK_SERVICE_STOCK_API_URL}
      - ENABLE_BACKGROUND_JOBS=true
    ports:
      - '7080:7070'
    networks:
      - pocketbase

networks:
  pocketbase:
