name: Backup Postgres Database

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  backup:
    name: Backup database
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Connect to server
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/bb_app
            docker exec "${{ vars.DB_CONTAINER }}" bash -c "
            PGPASSWORD='${{ secrets.DB_PASSWORD }}' pg_dump -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_DATABASE }} > /var/lib/postgresql/data/backup.sql
            "
            sudo cp /home/bb_app/data/postgres/backup.sql .
      - name: Download files
        run: |
          wget -q ftp://'${{ secrets.USERNAME }}':'${{ secrets.PASSWORD }}'@${{ secrets.HOST }}/backup.sql
      - name: Upload backup to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: Database backup
          path: backup.sql
          retention-days: 90
