name: Database Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract files
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/bb_app
            sudo zip -r /home/bb_app/data.zip data/
      - name: Download files
        run: |
          wget -q ftp://'${{ secrets.USERNAME }}':'${{ secrets.PASSWORD }}'@${{ secrets.HOST }}/data.zip
      - name: Upload postgres
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: data.zip
          retention-days: 7
